'use strict';

const OPERATION_STATUSES = Object.freeze({
  RECEIVED: 'RECEIVED',
  RESOLVING: 'RESOLVING',
  PLANNING: 'PLANNING',
  POLICY_REVIEW: 'POLICY_REVIEW',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  APPROVED: 'APPROVED',
  EXECUTING: 'EXECUTING',
  VALIDATING: 'VALIDATING',
  READY_TO_PUBLISH: 'READY_TO_PUBLISH',
  READY_TO_DEPLOY: 'READY_TO_DEPLOY',
  DEPLOYING: 'DEPLOYING',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  ROLLBACK_REQUIRED: 'ROLLBACK_REQUIRED',
  ROLLING_BACK: 'ROLLING_BACK',
  ROLLED_BACK: 'ROLLED_BACK',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
});

const TERMINAL_STATUSES = Object.freeze(new Set([
  OPERATION_STATUSES.COMPLETED,
  OPERATION_STATUSES.FAILED,
  OPERATION_STATUSES.ROLLED_BACK,
  OPERATION_STATUSES.REJECTED,
  OPERATION_STATUSES.CANCELLED,
  OPERATION_STATUSES.EXPIRED
]));

const INTENT_TYPES = Object.freeze({
  INSPECT: 'INSPECT',
  DIAGNOSE: 'DIAGNOSE',
  CODE_CHANGE: 'CODE_CHANGE',
  REFACTOR: 'REFACTOR',
  DEPENDENCY_UPDATE: 'DEPENDENCY_UPDATE',
  TEST: 'TEST',
  BUILD: 'BUILD',
  GIT_OPERATION: 'GIT_OPERATION',
  PULL_REQUEST: 'PULL_REQUEST',
  DEPLOY: 'DEPLOY',
  ROLLBACK: 'ROLLBACK',
  INFRASTRUCTURE: 'INFRASTRUCTURE',
  DATABASE_CHANGE: 'DATABASE_CHANGE'
});

const RISK_LEVELS = Object.freeze({ R0: 'R0', R1: 'R1', R2: 'R2', R3: 'R3', R4: 'R4' });

module.exports = { OPERATION_STATUSES, TERMINAL_STATUSES, INTENT_TYPES, RISK_LEVELS };
